// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HeavyBArgs {
    pub n: u32,
}

impl From<HeavyBArgs> for super::Reducer {
    fn from(args: HeavyBArgs) -> Self {
        Self::HeavyB { n: args.n }
    }
}

impl __sdk::InModule for HeavyBArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `heavy_b`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait heavy_b {
    /// Request that the remote module invoke the reducer `heavy_b` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`heavy_b:heavy_b_then`] to run a callback after the reducer completes.
    fn heavy_b(&self, n: u32) -> __sdk::Result<()> {
        self.heavy_b_then(n, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `heavy_b` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn heavy_b_then(
        &self,
        n: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl heavy_b for super::RemoteReducers {
    fn heavy_b_then(
        &self,
        n: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(HeavyBArgs { n }, callback)
    }
}
