// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HeavyAArgs {
    pub n: u32,
}

impl From<HeavyAArgs> for super::Reducer {
    fn from(args: HeavyAArgs) -> Self {
        Self::HeavyA { n: args.n }
    }
}

impl __sdk::InModule for HeavyAArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `heavy_a`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait heavy_a {
    /// Request that the remote module invoke the reducer `heavy_a` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`heavy_a:heavy_a_then`] to run a callback after the reducer completes.
    fn heavy_a(&self, n: u32) -> __sdk::Result<()> {
        self.heavy_a_then(n, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `heavy_a` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn heavy_a_then(
        &self,
        n: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl heavy_a for super::RemoteReducers {
    fn heavy_a_then(
        &self,
        n: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(HeavyAArgs { n }, callback)
    }
}
