// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReadD1Args {}

impl From<ReadD1Args> for super::Reducer {
    fn from(args: ReadD1Args) -> Self {
        Self::ReadD1
    }
}

impl __sdk::InModule for ReadD1Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `read_d_1`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait read_d_1 {
    /// Request that the remote module invoke the reducer `read_d_1` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`read_d_1:read_d_1_then`] to run a callback after the reducer completes.
    fn read_d_1(&self) -> __sdk::Result<()> {
        self.read_d_1_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `read_d_1` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn read_d_1_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl read_d_1 for super::RemoteReducers {
    fn read_d_1_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(ReadD1Args {}, callback)
    }
}
